### ISSUE TITLE
Problem with Matplotlib following installation of Marvin on MacOS

### ISSUE THREAD

**Issue by francbelf** [sdss/marvin#104]
I installed Marvin on two different MacOS machines. During installation marvin installs a new version of matplotlib for no apparent reason. Here's the extract from the installation terminal

Collecting matplotlib>=1.5.3 (from sdss-marvin)
  Downloading matplotlib-1.5.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (11.2MB)

after this, matplotlib stops working and I get the following warning if I load it in python

Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

I found a solution which fixes the problem here

http://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python

It would be good to either document this failure mode on the Marvin installation page or, better, to fix it.
Btw, I get the same problem on my MacBookPro running Mavericks and on my iMac running OS 10.8. In both computers I use an Anaconda installation of python.

**Comment by albireox** [comment]
Hey Francesco,

Thanks for reporting this. The problem seems to be that Python needs to be installed as a framework for the MacOS backend to work. Changing the backend for a non-cocoa based one solves the problem. A couple questions: before installing marvin, where you using anaconda or did you install it specifically for marvin; if you were already using anaconda, do you remember what version of matplotlib were you using before pip installing marvin updated it to the latest version (1.5.3)?

A possibility is that an older version of matplotlib may not require Python to be installed as a framework for the MacOS backend to work. If so, maybe we can relax the minimum version of matplotlib that we require (would need to do some research on that).

In any case, I have added some text about this issue, including your link, to PR #106, so at least the issue is documented.

**Comment by francbelf** [comment]
I was already using Anaconda before installing marvin. I do not know which version of matplotlib that came with, sorry.
