### ISSUE TITLE
Problem with ConvertToTool

### ISSUE THREAD

**Issue by francbelf** [sdss/marvin#105]
I get a problem using the ConvertToTool function with 'modelcube'. It works with 'cube' or 'spaxel', however I would like to use modelcube because I need to plot both the spaxel spectrum and its model. 

Convert to Cubes.  For brevity, let's only convert only the first object.  
r4.convertToTool('modelcube', limit=1)
Converting results to Marvin Modelcube objects
ERROR: TypeError: attribute name must be string, not 'NoneType' [marvin.tools.query.results]

TypeError                                 Traceback (most recent call last)
<ipython-input-81-6571a0e4bb22> in <module>()
      1 # Convert to Cubes.  For brevity, let's only convert only the first object.
----> 2 r4.convertToTool('modelcube', limit=1)

/Applications/anaconda/lib/python2.7/site-packages/marvin/tools/query/results.pyc in convertToTool(self, tooltype, limit)
    940                             template_kin=res.__getattribute__(
    941                             self._getRefName('template.name')),
--> 942                             mode=self.mode) for res in self.results[0:limit]]

TypeError: attribute name must be string, not 'NoneType'

**Comment by havok2063** [comment]
If you are running the query from the Shanghai tutorial, then this error is most likely because the query is not returning the necessary default parameters needed to instantiate a ModelCube.  The ModelCube also needs the bintype and template parameters returned.  The error is caused when Marvin Results looks for those parameters and cannot find them.

However, this should not occur since the ModelCube defaults to the unbinned version and MILESHC library when nothing is input.  I will to expand this method to be more robust to that.  It's not a difficult fix.

**Comment by havok2063** [comment]
This is now fixed and will be available in the next release.
