### ISSUE TITLE
Move documentation to readthedocs

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#124]
Little by little our documentation is starting to take form and we are starting to find that, as we develop aggressively, some of the text, keywords, known issues, etc that we mention are valid for some versions of Marvin but nor for others.

To keep a version control of our documentation we should consider moving to readthedocs (or other similarly hosted service) so that we can link documentation versions to released versions. Now that all the code in Marvin is public I don't see a strong reason not to do this soon. It would also save us some time in having to deploy any new change in the documentation at Utah.

Alternatively, if we don't want to make the documentation public, we could consider installing readthedocs at Utah. I have had a look and all the code is public, but it does not seem like an easy thing to install.

**Comment by havok2063** [comment]
I'm not opposed to this.  I think versioning our documentation is a good idea.   What's the connection with the Sphinx documentation?  Can we still develop and write it in the same manner as we do now?  I'd like to keep it that way as much as possible.  I'm less on board if it requires extra steps than what we do now.

**Comment by albireox** [comment]
Yes, I did some tests with readthedocs at some point in time. You basically link it to a github repo, point it to the location of the sphinx documentation, and it builds a new version of the documentation for each release, and (I think) updates the latest version of the documentation every time somebody commits something. There are different kinds of hooks and such, but once configured it should be quite straight-forward.

**Comment by bretthandrews** [comment]
I'm on board, especially if there's a quicker iteration loop without the Utah step.

**Comment by albireox** [comment]
Ok. I may set up a test account and we can see how it works for a while and if we like it, we can make the suggestion of moving the docs there.

**Comment by havok2063** [comment]
While in principle this is a good thing, we also aren't a lone piece of software.  One reason having the documentation on api.sdss.org/docs is that all of the SDSS documentation would then live together, rather than being spread out over the internet, which makes more sense.  If we can create an SDSS readthedocs hub, and start to build a hierarchy inside that, then ok.  Otherwise maybe we should think about it some more.   In any case, we should keep the api.sdss.org/docs/marvin documentation up-to-date with readthedocs.
