### ISSUE TITLE
Rename NSA Display Tab

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#187]
I was showing Lluís Galbany the new features of Marvin 2.1, and he asked what does NSA stand for. He works with IFU data (PMAS, CALIFA, and MaNGA more recently), so he's not a beginner-level user.

Suggestions:
- rename tab: "Sample Properties"
- change "NSA Parameters" to "NASA-Sloan Atlas (NSA) Properties" 

Similarly, we should explain the NSA more fully in the docs and the "Use this Cube in Python" snippet

**Comment by havok2063** [comment]
Relevant #184

**Comment by joelbrownstein** [comment]
Wherever possible/appropriate add a link to the official documention, for e.g.
http://www.sdss.org/dr13/manga/manga-target-selection/nsa/

On Feb 22, 2017, at 12:31 PM, Brett Andrews <notifications@github.com<mailto:notifications@github.com>> wrote:


I was showing Lluís Galbany the new features of Marvin 2.1, and he asked what does NSA stand for. He works with IFU data (PMAS, CALIFA, and MaNGA more recently), so he's not a beginner-level user.

Suggestions:

  *   rename tab: "Sample Properties"
  *   change "NSA Parameters" to "NASA-Sloan Atlas (NSA) Properties"

Similarly, we should explain the NSA more fully in the docs and the "Use this Cube in Python" snippet

**Comment by havok2063** [comment]
I can change "NSA Parameters" to "NASA-Sloan Atlas (NSA) Properties" but I will need to increase the column span of the table.  That means the plots will be smaller and there is more white space in the table columns.   Otherwise it's too long, the text wraps and pushes the table down.

I suggest renaming 'NSA Display' to "Galaxy Properties" .  "Sample Properties" suggests properties of the entire sample, rather than the single galaxy.

**Comment by bretthandrews** [comment]
I'm on board with keeping "NSA Parameters" but linking to the website and "Galaxy Properties" works for me.

**Comment by havok2063** [comment]
Awesome.  I'll make the changes and commit them.

**Comment by havok2063** [comment]
This is fixed in recent update, and pushed in 2.1.2 patch.
