### ISSUE TITLE
bpt fig is not easily modifiable

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#190]
Someone pointed out that the matplotlib figure object currently output by the BPT utility method is just the figure handler, and does not easily contain the figures themselves.  The internal figures are not easily accessible and modifiable by the user, except via hacking hidden attributes on the figure handler.   

We should think about revising this, possibly in line with revising our general figure handling in Marvin.

**Comment by albireox** [comment]
Well, the figure is really the figure ... What it contains, in an arguably convoluted way, are the axes that contain the individual plots. Modifying the figure is certainly not trivial, and requires some in-depth knowledge of Matplotlib. I don't know if we want to spend a lot of effort in reinventing the matplotlib wheel (ultimately, the user has all the information to generate their own plots, it they want), but I'm happy to brainstorm.

What I think we need to make sure is that the plots we produce serve the majority of the people and provide some documentation and examples (that's on me) about how the matplotlib figure is organised and how to modify things so that power users have a window to modifying the plots.
