### ISSUE TITLE
pip upgrade may not install new things as fresh install

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#210]
Tom Peterken had a problem after pip upgrading to the latest marvin.  He got this error when trying to access remote objects.

```
A full example traceback: I'm using Spyder 3.0.0, Python 2.7.12, on Linux.
In [42]: maps = Maps(mangaid='1-209232', mode='remote')
Traceback (most recent call last): File "<ipython-input-42-8620e8b652ad>", line 1, in <module>
    maps = Maps(mangaid='1-209232', mode='remote')
File "/home/ppxtgp/anaconda2/lib/python2.7/site-packages/marvin/tools/maps.py", line 204, in __init__
    self._load_maps_from_api()
File "/home/ppxtgp/anaconda2/lib/python2.7/site-packages/marvin/tools/maps.py", line 436, in _load_maps_from_api
    raise marvin.core.exceptions.MarvinError('remote maps has a different plateifu!')
MarvinError: remote maps has a different plateifu!.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.
```

He had marvin version 2.0 and did a `pip install --upgrade sdss-marvin` to get 2.1.2.  He then received the above error when attempting to access cubes and maps remotely, either with plateifu or mangaid.   He then `pip uninstall sdss-marvin` and did a fresh `pip install sdss-marvin` and now everything works.  

I'm wondering if everything gets upgraded properly when we upgrade marvin from a previous version which includes changes in submodules.

**Comment by joelbrownstein** [comment]
This is certainly an advantage of the dockerized version of marvin since the pip install would run whenever the docker image is rebuilt so the user would not themselves have to run pip upgrade (although they could if they didn't want to run the latest docker image).

On Mar 21, 2017, at 11:33 AM, Brian Cherinka <notifications@github.com<mailto:notifications@github.com>> wrote:


Tom Peterken had a problem after pip upgrading to the latest marvin. He got this error when trying to access remote objects.

A full example traceback: I'm using Spyder 3.0.0, Python 2.7.12, on Linux.
In [42]: maps = Maps(mangaid='1-209232', mode='remote')
Traceback (most recent call last): File "<ipython-input-42-8620e8b652ad>", line 1, in <module>
    maps = Maps(mangaid='1-209232', mode='remote')
File "/home/ppxtgp/anaconda2/lib/python2.7/site-packages/marvin/tools/maps.py", line 204, in __init__
    self._load_maps_from_api()
File "/home/ppxtgp/anaconda2/lib/python2.7/site-packages/marvin/tools/maps.py", line 436, in _load_maps_from_api
    raise marvin.core.exceptions.MarvinError('remote maps has a different plateifu!')
MarvinError: remote maps has a different plateifu!.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.


He had marvin version 2.0 and did a pip install --upgrade sdss-marvin to get 2.1.2. He then received the above error when attempting to access cubes and maps remotely, either with plateifu or mangaid. He then pip uninstall sdss-marvin and did a fresh pip install sdss-marvin and now everything works.

I'm wondering if everything gets upgraded properly when we upgrade marvin from a previous version which includes changes in submodules.

**Comment by albireox** [comment]
The changes in the submodules should not matter as long as the person who created the distribution that is uploaded to PyPI does so with the up-to-date version of the submodules. But if that's not the case, everybody that pip-upgrades Marvin should have the same problem ...

**Comment by havok2063** [comment]
I think we can close this for now.  We no longer seem to be having this issue with the later releases.
