### ISSUE TITLE
Web maps set spaxels to gray when any bit is set

### ISSUE THREAD

**Issue by francbelf** [sdss/marvin#229]
The web version of the D4000 maps is full of holes while the same map obtained from marvin.tools is perfectly ok

For example
maps = Maps(plateifu='8077-12705')

In [59]: d4000 = maps.getMap('specindex', channel='d4000')

In [60]: d4000.plot(cmap='viridis')
I get this from the tools
![example](https://cloud.githubusercontent.com/assets/20231691/25411514/ef2df388-29d1-11e7-858e-5641bcc2631d.png)

While the web gives this

**Comment by francbelf** [comment]
![screen shot 2017-04-25 at 16 14 38](https://cloud.githubusercontent.com/assets/20231691/25411565/55fc4452-29d2-11e7-9bab-379fcc49e6b9.png)

**Comment by bretthandrews** [comment]
#231

**Comment by bretthandrews** [comment]
Linked to Issue #231

**Comment by bretthandrews** [comment]
Both the web and the tools only hatch spaxels with SNR < 1.

The tools show spaxels with the NOVALUE, UNRELIABLE, MATHERROR, FITFAILED, and DONOTUSE [DAPPIXMASK](https://trac.sdss.org/wiki/MANGA/TRM/TRM_ActiveDev/DAPMetaData#MANGA_DAPPIXMASK) flags set as gray. The web _should_ also do this, but there was a javascript error that would set spaxels to gray if any bits were set. The web code is also inconsistent with the tools in that it is setup to hatch spaxels with UNRELIABLE, MATHERROR, FITFAILED, and DONOTUSE bits set (but doesn't because of the bug). We need to make the web and tools maps consistent.

We could hatch spaxels with all of these flags set and only use gray for spaxels with NOCOV.

**Comment by bretthandrews** [comment]
It seems that the web does not do quantile clipping for D4000 (see `quantileClip` in `heatmap.js`.
