### ISSUE TITLE
Problem with query

### ISSUE THREAD

**Issue by francbelf** [sdss/marvin#261]
I tried the following query

from marvin.tools.query import doQuery
q, r = doQuery(searchfilter='nsa.sersic_logmass >= 10 and nsa.sersic_logmass <= 11', returnparams='emline_gflux_ha_6564')

and got the following error message

MarvinError: API Query call failed: Requests Http Status Error: 404 Client Error: Not Found for url: https://api.sdss.org/marvin2/api/query/cubes/.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

**Comment by havok2063** [comment]
This is the standard intermittent error we've been getting for a while now.  Because it goes a long time before erroring, and then upon retry, is both successful and fast, one possibility is that the query is being done the first time, gets cached, and something bad happens when sending it back through the HTTP response.  The second attempt works since it access the cache?

May also be related to these recurring database errors we get
`DatabaseError: (psycopg2.DatabaseError) lost synchronization with server: got message type "6", length 825622528`

**Comment by havok2063** [comment]
I think this is now fixed in the MPL6 release
