### ISSUE TITLE
Query leads to 404 Error

### ISSUE THREAD

**Issue by kbwestfall** [sdss/marvin#269]
I tried this query:

nsa.sersic_logmass > 10 and spaxelprop.stellar_sigma > 200

and got a 404 error.  Is this because of a timeout or something else?  Is there a way to catch timeouts and provide a page that says the query timed out, or is that already supposed to happen?

I started with a query that was just spaxelprop.stellar_sigma > 200 , hit enter, got impatient and realized this query was probably too broad, hit the button to stop the webpage from loading, then entered the query above.  I imagine getting impatient with a query result could be a common occurrence.  Could I have broken something with this procedure?  Is there a better way that a user can stop an executed query?

**Comment by havok2063** [comment]
This is related to #261.   The short is this is an error that should not be occurring.  

Are you doing this on the web or in the Tools?  The web is not recommended to do this.  

With the tools, I think this is due to strange db related things that I cannot figure out.   There is a timeout of 5 minutes, but that would produce a different error.  So I don't think it's that.  With these weird 404 errors, normally if you rerun the query it will work, and be fast.  

Yeah, your original query may have been broad.  It's also querying all bintypes.  Try it only with SPX bintypes.  No, I don't think there's a real good way for a user to stop an already submitted query.  We could try to make something to do this, but it would involve db process id lookups and issuing db kill transaction sql commands.

**Comment by kbwestfall** [comment]
This was in the web.  I'll give the tools a shot.  Just to explain what could be common user behavior, I had been running some tests on a galaxy that had low dispersion and wanted to understand how the test would behave for a galaxy with a larger dispersion.  I specifically wanted one in one of the smaller bundles so I spent some time just trolling my qa plots on the SAS, then I spent some time just trolling the plate montage on Marvin.  Finally, I just decided to run a web query because I thought I could quickly find a galaxy with high dispersion observed by a small bundle.  I'm not sure generally useful this is (probably not because David Wake has warned us again and again to not use galaxies selected by bundle size as a statistical sample), but this is one case where allowing users to query on bundle size would be useful.

I didn't let the query run for 5 minutes, so it definitely wasn't a time out.

I didn't realize the query would run on all bintypes, although thinking about it, it makes sense that it would.

**Comment by havok2063** [comment]
Ok, this makes sense.  You can try something like `nsa.sersic_logmass > 10 and spaxelprop.stellar_sigma > 200 and ifu.name=19* and bintype.name==SPX`.  

I tried this in the tools that ran in 15 seconds and returned ~8700 spaxels.  If you want all of them back at once, just add `limit=10000` to the query.  Then you'll have the whole set to manipulate.   
```
q = Query(searchfilter='nsa.sersic_logmass > 10 and stellar_sigma > 200 and bintype.name==SPX and ifu.name=19*', mode='remote')
r = q.run()
r.totalcount
8783
r.query_runtime.total_seconds()
15.68395
```

**Comment by havok2063** [comment]
Closing this until it resurfaces.
