### ISSUE TITLE
problem with installing marvin on my laptop

### ISSUE THREAD

**Issue by viniwiede** [sdss/marvin#294]
I tried to install marvin on my laptop with the command: _pip install sdss-marvin_
But  then this error appears:
_Command "C:\Users\Vinzenz\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Vinzenz\\AppData\\Local\\Temp\\pip-build-87jgajxr\\python-Levenshtein\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Vinzenz\AppData\Local\Temp\pip-9j35we_q-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Vinzenz\AppData\Local\Temp\pip-build-87jgajxr\python-Levenshtein\_
I am using Anaconda3 on a Windows 64bit computer.
I do not know how to fix this error. Could you please help me with that?
Thank you

**Comment by albireox** [comment]
Hi @viniwiede. I'm afraid marvin is not supported in Windows at this time (we should make that explicit in the documentation). Even if you get to install marvin, which may not be possible because some of the dependencies may be Mac/Linux-only, marvin is unlikely to run properly. At this time we don't have plans to provide support for Windows.

I'd recommend that you get a Linux installation in your machine (you can do it in a virtual box to start with) or that you install marvin on a Linux or Mac machine.

I'm going to close the issue as wontfix, but please feel free to continue commenting on this thread if you need further help.
