### ISSUE TITLE
Mask issue with mapplot.set_extent when sky_coords=True

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#325]
from marvin.tools.maps import Maps
import marvin.utils.plot.map as mapplot

maps = Maps(plateifu='8485-1901')
ha = maps['emline_gflux_ha_6564']
low_snr = mapplot.mask_low_snr(value=ha.value, ivar=ha.ivar, snr_min=10)
#neg_values = mapplot.mask_neg_values(value=ha.value)

extent = mapplot.set_extent(cube_size=(ha.shape), sky_coords=True)

fig, ax = mapplot.plot(dapmap=ha, mask=low_snr, imshow_kws={'extent':extent})

Produces a plot with a quarter of the mask showing:
![screen shot 2018-02-20 at 11 15 35 am](https://user-images.githubusercontent.com/12090407/36435344-68f3c6c6-162f-11e8-9415-0a5928295c8a.png)

sky_coords=False or not passing extent to imshow_kws produces a correct plot.

**Comment by bretthandrews** [comment]
@KateRowlands thanks for finding this bug!

**Comment by bretthandrews** [comment]
FYI you can set sky coordinates from the `mapplot.plot()` call like this:
`fig, ax = mapplot.plot(dapmap=ha, mask=low_snr, sky_coords=True)`

instead of:
`extent = mapplot.set_extent(cube_size=(ha.shape), sky_coords=True)
fig, ax = mapplot.plot(dapmap=ha, mask=low_snr, imshow_kws={'extent':extent})`

**Comment by havok2063** [comment]
Reopening.

**Comment by bretthandrews** [comment]
`mapplot.set_extent` has been made an internal function, so users should set `sky_coords=True` in call to `mapplot.plot`.
