### ISSUE TITLE
Colorbar label issue  in mapplot.plot

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#330]
maps = Maps(plateifu='8485-1901')
ha = maps['emline_gflux_ha_6564']

fig, ax = mapplot.plot(dapmap=ha, value=ha.value, symmetric=True,  log_cb=True)

Produces a plot with no colorbar value labels:
![screen shot 2018-02-20 at 4 15 19 pm](https://user-images.githubusercontent.com/12090407/36449613-4be31166-1659-11e8-8dc0-076e397adc72.png)

But if symmetric=False then the plot is produced correctly:
![screen shot 2018-02-20 at 4 16 12 pm](https://user-images.githubusercontent.com/12090407/36449650-6744af1e-1659-11e8-8fbc-27803ba2a596.png)

**Comment by bretthandrews** [comment]
@KateRowlands the `symmetric` keyword makes the colorbar symmetric about 0, so the values would be negative, hence the warning:
```
WARNING: invalid value encountered in log10
```
The `symmetric` keyword is intended for velocity plots (or another quantity that naturally diverges from zero) and is not meant to be used with the `log_cb` option. I've added a warning to let users know why this issue is occurring.

**Comment by KateRowlands** [comment]
Hi Brett,

I think there needs to be an explicit catch in the code which does not allow the user to use the symmetric and log_cb options together, as people don't pay attention to warnings or will try to do stupid things (like log10 of a negative number). Also, some users may expect the colorbar to be logged and then made symmetric, so the usage is ambiguous.

**Comment by havok2063** [comment]
Reopening.

**Comment by bretthandrews** [comment]
Marvin now throws an `AssertionError` if you try to create a symmetric logarithmic color bar.

**Comment by bretthandrews** [comment]
Fixed in 5f01637f4fb64bc13d60a9bfdc2ad8a255c151ba
