### ISSUE TITLE
doc issue with extent in mapplot

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#351]
Kate
Tools - mapplot
It is unclear how to pass the result of mapplot.set_extent to mapplot.plot. Same goes for mapplot.set_patch_style. Additional line of code example needed e.g fig, ax = mapplot.plot(dapmap=ha, mask=low_snr, imshow_kws={'extent':extent}).

Related to Issue #327 

Per comment thread, `set_extent` should be hidden, docs made clear to use `ax.axis`

**Comment by bretthandrews** [comment]
Fixed in 9222091b6decede385d218f12137c4babdc145e3. `mapplot.set_patch_style` and `mapplot.set_extent` have been converted into internal functions. There are examples in the Plotting Tutorial on how to create zoom in maps and how to change the hatch appearance (effectively what those functions had been intended to do).
