### ISSUE TITLE
maps view in galaxy page very slow

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#371]
Eric
Web - Galaxy page - maps view

Very slow in moving mouse upon maps, in poping out coordinates and values, in extracting corresponding spectra (after clicking). I don't know if this issue only occurs on me (located in Beijing). Used to be much faster half a year ago.

**Comment by havok2063** [comment]
Here are some timing updates from Eric. 
```
I've recently found the speed on Safari is good enough, though this browser is not recommended. The slowness on Chrome is still happening. Maybe the slowness is due to html5 feature?

On Chrome (Safari), the responding time is as follows:
scrolling up and down the web page, 10-20s (Safari, immediately)
moving the mouse tracker on the maps, 15-30s (Safari, almost immediately)
moving the mouse tracker on the optical image, both immediately
extracting spectra after clicking, 10-15s (Safari, 3-5s)
ps: the upper time limit above is usually for the initial move and the lower time limit is usually for constant same moves.

Last year and the year before last, Chrome had the same speed as what Safari has now, as listed above.

Besides, the speed depends slightly on the time in a day and scarcely on the network I’m in.

At least Safari (or maybe some other browsers) is an acceptable choice to me for now.
```
 It appears on Chrome accessing the maps and spaxels is ~10x slower than it used to be.   A lot has changed since last year.  This is the list of the big things I think have changed.
- moved database to new machine
- added MPL-6
- added DataModels
- changed Spaxels and Maps to use Quantities
- made some Tools only use files remotely (are we sure this is turned off for web stuff?)

The Javascript libraries we use have not been updated in awhile. B

**Comment by joelbrownstein** [comment]
Hi Brian,

I have been using Safari for Marvin and have not found a single feature that is lacking, although I would like to see one if you can prove me wrong.

Benchmarks also prove that Safari is the fastest browser.

I think it is time to drop the Safari warning.   Frankly there are NO websites that I can think of other than Marvin that have such a warning.  I’m not saying Safari is 100% compliant with HTML5.  I am just saying no one really cares to see the warning.   It is extremely annoying.

Cheers, Joel

On Mar 7, 2018, at 12:14 PM, Brian Cherinka <notifications@github.com<mailto:notifications@github.com>> wrote:


Here are some timing updates from Eric.

I've recently found the speed on Safari is good enough, though this browser is not recommended. The slowness on Chrome is still happening. Maybe the slowness is due to html5 feature?

On Chrome (Safari), the responding time is as follows:
scrolling up and down the web page, 10-20s (Safari, immediately)
moving the mouse tracker on the maps, 15-30s (Safari, almost immediately)
moving the mouse tracker on the optical image, both immediately
extracting spectra after clicking, 10-15s (Safari, 3-5s)
ps: the upper time limit above is usually for the initial move and the lower time limit is usually for constant same moves.

Last year and the year before last, Chrome had the same speed as what Safari has now, as listed above.

Besides, the speed depends slightly on the time in a day and scarcely on the network I’m in.

At least Safari (or maybe some other browsers) is an acceptable choice to me for now.


It appears on Chrome accessing the maps and spaxels is ~10x slower than it used to be. A lot has changed since last year. This is the list of the big things I think have changed.

  *   moved database to new machine
  *   added MPL-6
  *   added DataModels
  *   changed Spaxels and Maps to use Quantities
  *   made some Tools only use files remotely (are we sure this is turned off for web stuff?)

The Javascript libraries we use have not been updated in awhile. B

**Comment by havok2063** [comment]
I agree it's annoying to have to constantly see the banner.  That was not the original behavior.  I think we were supposed to only see it once.  I'm also fine deprecating the banner if people agree.  Maybe the newer Safari's are better.  I still have extreme login problems using Safari.  However, the point here is that Chrome is slower than it used to be.  Maybe that's an issue with Chrome changing something internal, in which case there's not much we can do about that.  Maybe it's an issue with Beijing and firewalls.  Or maybe it's something we changed, in which case we should at least look into it.

**Comment by havok2063** [comment]
Updates from Eric after I asked to test with MPL-5 and Firefox.

```
I have been testing with MPL-6. I just tried MPL-5 and found the same slowdown (on Chrome) on the same scale. During the interaction with Marvin on Chrome, other apps on Mac are also slowed down, which may imply it’s occupying much CPU on my local machine.

I’ve tried Firefox and it’s as fast as Safari. Amazingly, after I upgraded to the latest Chrome (Version 65.0.3325.146 (Official Build) (64-bit)), it immediately became as fast. I didn’t remember the last version I was using (Chrome said it was "nearly up to date”).

Safari Version 9.1.3 (11601.7.8)
Always on Mac OS X El Capitan 10.11.6 (15G1004)

Besides, I’ve heard the firewall does not cause this kind of slowdown for anything, so we don’t need to worry about that.

So I think the issue is solved for practical purposes.
```
Given this, I'm calling this fixed.
