### ISSUE TITLE
Cube units do not persist under axis reordering

### ISSUE THREAD

**Issue by zpace** [sdss/marvin#374]
reordering axes of a flux cube by calling `cube.flux.T` or similar yields a marvin `DataCube`, but the units then revert to being uninitialized.

Ex:

    cube = Cube(plateifu='8982-1902')
    # moving wavelength axis to final position, to make broadcasting easier
    print(np.moveaxis(cube.flux, 0, -1).unit)

    None
 
It would be neat if this just worked, but it should be documented (or maybe even throw an error explicitly) if that's not intended functionality

**Comment by zpace** [comment]
Also there is similar behavior under `np.einsum`: in this case, a simple numpy array is returned, rather than a `DataCube`

    e = np.random.randn(10, len(cube.flux.wavelength))
    a = np.einsum('ql,lij->qij', e, cube.flux)

**Comment by albireox** [comment]
Thanks for the report @zpace and sorry for the delay. This was easy enough to fix. I was not resetting the unit in my `__array_finalize__` so it got lost when you performed an operation on the array that didn't call `__new__`. Adding `self._set_unit(getattr(obj, 'unit', None))` fixes the problem. I'll add some tests and create a pull request but this should be fixed in the next release.
