### ISSUE TITLE
creating categorial colorbar in mapplot produces different plots with dapmap

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#376]
Following the example of a qualitative colorbar here http://sdss-marvin.readthedocs.io/en/stable/tutorials/plotting-tutorial.html#qualitative-colorbar-new-in-version-2-1-4, I get a different plot output with `mapplot.plot` when different `dapmaps` are used. 

See the example in WHAN exercise solution, but relevant code here.  E.g. using `dapmap=niiha` produces different output than `dapmap=ewha`.

```
plateifu = '8485-1901'

from marvin.tools.maps import Maps
import marvin.utils.plot.map as mapplot
maps = Maps(plateifu=plateifu)
niiha = maps.emline_gflux_nii_6585/maps.emline_gflux_ha_6564
ewha = maps['emline_sew_ha_6564']
ewnii = maps['emline_sew_nii_6585']
import numpy as np
logniiha = np.log10(niiha.value)

psf = (logniiha < -0.4) & (ewha.value > 3)
sagn = (logniiha > -0.4) & (ewha.value > 6)
wagn = (logniiha > -0.4) & ((ewha.value > 3) & (ewha.value < 6))
rg = ewha.value < 3
pg = (ewha.value < 0.5) & (ewnii.value < 0.5) 

value = ewha.value.copy()
value[psf] = 1     # pure star-forming 
value[sagn] = 2    # strong agn
value[wagn] = 3    # weak agn
value[rg] = 4      # retired galaxies
value[pg] = 5      # passive galaxies

nocov = ewha.pixmask.get_mask('NOCOV')

fig, ax, cb = mapplot.plot(dapmap=niiha, value=value, cmap=cmap, mask=nocov, return_cb=True, 
                           cbrange=(0.5, 5.5), title='WHAN Diagram {0}'.format(plateifu))

```

**Comment by bretthandrews** [comment]
`mapplot.plot()` uses the `dapmap` input to automatically set the `ivar` and `mask` for deciding which spaxels to show (unless manually specified). Since this categorical colormap has a complicated selection function, it would be best to create a custom ivar to use.

This use case did highlight the unwanted side-effect of `mapplot.plot()` not masking spaxels with `ivar == np.nan``, which has been fixed.
