### ISSUE TITLE
Is fuzzywuzzy too fuzzy?

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#382]
fuzzywuzzy believes that "stellar_sigmacorr" is a close enough to "stellar_sigma" to not raise an error.

```
from marvin.tools.maps import Maps
maps =Maps('8485-1901')
assert (maps['stellar_sigmacorr'] == maps['stellar_sigma']).all()
```

More generally, if a user enters the name of an HDU from the maps file that does not have a direct analog in the `Maps` object datamodel (e.g., "stellar_sigmacorr"), then it can just choose the closest match that has a similar name but very different data.

```
import os
from os.path import join

from astropy.io import fits

from marvin import config
from marvin.tools.maps import Maps

plate = '8485'
ifu = '1901'
plateifu = '-'.join((plate, ifu))
bintemp = 'SPX-GAU-MILESHC'

# Load file via Astropy
drpver, dapver = config.lookUpVersions()
path = join(os.environ['MANGA_SPECTRO_ANALYSIS'], drpver, dapver, bintemp, plate, ifu,
            'manga-{0}-{1}-MAPS-{2}.fits.gz'.format(plate, ifu, bintemp))
hdus = fits.open(path)

# Loads maps object in Marvin
maps = Maps(plateifu)

for hdu in hdus[1:]:
    try:
        print(hdu.name, maps[hdu.name].datamodel.full())
    except ValueError as ee:
        print('   Ambiguous:', hdu.name)
```

which prints:
```
   Ambiguous: SPX_SKYCOO
   Ambiguous: SPX_ELLCOO
SPX_MFLUX spx_mflux
SPX_MFLUX_IVAR spx_mflux
SPX_SNR spx_snr
   Ambiguous: BINID
   Ambiguous: BIN_LWSKYCOO
   Ambiguous: BIN_LWELLCOO
BIN_AREA bin_area
BIN_FAREA bin_farea
BIN_MFLUX bin_mflux
BIN_MFLUX_IVAR bin_mflux
BIN_MFLUX_MASK bin_mflux
BIN_SNR bin_snr
STELLAR_VEL stellar_vel
STELLAR_VEL_IVAR stellar_vel
STELLAR_VEL_MASK stellar_vel
STELLAR_SIGMA stellar_sigma
STELLAR_SIGMA_IVAR stellar_sigma
STELLAR_SIGMA_MASK stellar_sigma
STELLAR_SIGMACORR stellar_sigma
   Ambiguous: STELLAR_CONT_FRESID
STELLAR_CONT_RCHI2 stellar_cont_rchi2
   Ambiguous: EMLINE_SFLUX
   Ambiguous: EMLINE_SFLUX_IVAR
EMLINE_SFLUX_MASK emline_sflux_ha_6564
   Ambiguous: EMLINE_SEW
   Ambiguous: EMLINE_SEW_IVAR
   Ambiguous: EMLINE_SEW_MASK
   Ambiguous: EMLINE_GFLUX
   Ambiguous: EMLINE_GFLUX_IVAR
EMLINE_GFLUX_MASK emline_gflux_ha_6564
   Ambiguous: EMLINE_GEW
   Ambiguous: EMLINE_GEW_IVAR
   Ambiguous: EMLINE_GEW_MASK
   Ambiguous: EMLINE_GVEL
   Ambiguous: EMLINE_GVEL_IVAR
   Ambiguous: EMLINE_GVEL_MASK
   Ambiguous: EMLINE_GSIGMA
   Ambiguous: EMLINE_GSIGMA_IVAR
EMLINE_GSIGMA_MASK emline_gsigma_ha_6564
   Ambiguous: EMLINE_INSTSIGMA
   Ambiguous: EMLINE_TPLSIGMA
   Ambiguous: SPECINDEX
SPECINDEX_IVAR specindex_mgiir
SPECINDEX_MASK specindex_cahk
   Ambiguous: SPECINDEX_CORR
```
Takeaways:
- often the IVAR and MASK HDUs will map to the main quantity
- "EMLINE_\* _MASK" maps to "emline_\* _ha_6564"
- "SPECINDEX_IVAR" maps to "specindex_mgiir"
- "SPECINDEX_MASK" maps to "specindex_cahk"
- "STELLAR_SIGMACORR" maps to "stellar_sigma"

**Comment by bretthandrews** [comment]
I just found this: `maps.getMap('STELLAR_SIGMACORR', exact=True)` which throws an error (as desired). We may still want to raise an error if one of the above situations occurs.

**Comment by albireox** [comment]
So, I think there are two problems here (maybe more). The first, related to `STELLAR_SIGMACORR` is that for some reason (either changes in the data model or a snafu on my part), `STELLAR_SIGMACORR` is listed as a `MultiChannelProperty` without any channel in the MPL-6 data model, when it should be a normal property. As such, it doesn't appear in the datamodel at all and the fuzzy search finds the closest match, `STELLAR_SIGMA`. That's easy to fix by making `STELLAR_SIGMACORR` a normal property.

The second problem is that you cannot really search for things with `_MASK` or `_IVAR` since those are not channels. We consolidate ivar and mask inside the property, which is `name_channel`. So, there is no `SPECINDEX_IVAR` and fuzzywuzzy tries to match it to the closest thing, in this cases `specindex_mgiir`. I still think we should do something about it. Maybe we should check all fuzzy queries and raise an error if they contain `_ivar` or `_mask`. None of our properties or channels should contain those words so I think it's safe.

**Comment by albireox** [comment]
Fixed. See da0f85d0b1de8ba2996fbca83beda263439736d8 and 969dd4a7a0e032d160b573621a8f3e085c2040eb.
