### ISSUE TITLE
Trouble with bintype='VOR10' in MPL-6

### ISSUE THREAD

**Issue by khrrubin** [sdss/marvin#390]
Hi all,

I'd like to read the VOR10-GAU-MILESHC model cubes associated with MPL-6 into Marvin.  However, when I try, e.g., 

MCube = ModelCube(plateifu='7443-6102', bintype='VOR10')

I'm told that 'VOR10' is an invalid bintype.  (On the other hand, 

MCube = ModelCube(plateifu='7443-6102', bintype='HYB10')

works just fine.)

Many thanks for your assistance with this!

Kate

**Comment by havok2063** [comment]
Hi Kate, 

In the latest patch of Marvin we removed the VOR10 option from MPL-6 because these files did not get loaded into the database.  As you've discovered this prohibits the use of the files which do exist.  In a recent fix we have put the VOR10 bintypes back into Marvin so people can use VOR10 files in Marvin, but we haven't yet pushed that fix back into Marvin.  We will probably release an updated patch with all our latest fixes next week.  

Cheers, Brian

**Comment by khrrubin** [comment]
Great, thanks for this Brian!  I'll keep an eye out for the patch.

Best, Kate
