### ISSUE TITLE
Error: could not get spaxel

### ISSUE THREAD

**Issue by AMWeijmans** [sdss/marvin#391]
For galaxy 8141-6101: when toggling map view, I get:

Error : Error: Could not get spaxel: No row was found for one()

However, if I then select DAP maps to display, they do show.
This also happened for galaxy 8250-3702, all other galaxies I looked at were fine.

**Comment by havok2063** [comment]
Thanks, Anne-Marie.  Digging into this a bit it seems the fundamental issue is that the DAP model cube spaxels for these galaxies (and about 30 others) for MPL-6 did not get loaded in the database.  So the web-spaxel view fails because it's trying to find and plot the model fits when they don't exist.  Thanks for finding this.  I'll load them in and let you know when things are fixed.

**Comment by havok2063** [comment]
I've now added all the model spaxels into the database for all the missing galaxies, ~30 SPX and ~30 HYB10.  You should now be able to see and use the map/spec view on the web for these galaxies.
