### ISSUE TITLE
Trouble accessing images

### ISSUE THREAD

**Issue by goyarzun** [sdss/marvin#406]
I am unable to access images remotely nor download them. Marvin-web display doesn’t seem to work either. The errors I am getting are the following:

For remote image access, the code is:

**from marvin.utils.general.images import showImage
from marvin.utils.general.general import getWCSFromPng
plateifu='8332-9102’
image = showImage(plateifu=plateifu, show_image=False)
pixels=image.load()
w = getWCSFromPng(image.filename)**

The error I get is:
**marvin.core.exceptions.MarvinError: Cannot open image https://data.sdss.org/sas/mangawork/manga/spectro/redux/v2_0_1/8332/stack/images/9102.png: [Errno 2] No such file or directory: 'https://data.sdss.org/sas/mangawork/manga/spectro/redux/v2_0_1/8332/stack/images/9102.png’.**

Trying a different plate-ifu does not solve it. I also tried to download the image using getImagesByList(), but I get the same error as in MarvinWeb:

**Unknown exception: (psycopg2.OperationalError) FATAL:  password authentication failed for user "sdss"**

Thanks for looking into this!
Grecco

**Comment by havok2063** [comment]
Hi Grecco, 

You are getting the error ` [Errno 2] No such file or directory` when running `w = getWCSFromPng(image.filename)` because it is attempting to open a local image file with a remote url to the file.  It will not be able to open that.  This probably worked before because you already had the previous images downloaded and stored locally on disk.  

I will update the `getWCSFromPng(image.filename)` so you can provide either an image filepath or the PIL Image object itself, which you already grabbed here `image = showImage(plateifu=plateifu, show_image=False)`.  This will be provided in a later update. 

As for the authentication error, someone had changed the password that Marvin needs to access the database.  We have fixed this on the server.  You should now be able to use the `getImagesByList` method, and the web should be behaving normally again.   

Cheers, Brian

**Comment by goyarzun** [comment]
Hi Brian,

Everything is working now. Thank you!

Best,
Grecco
