### ISSUE TITLE
some API requests returns a Sentry RateLimited error

### ISSUE THREAD

**Issue by sjshamsi** [sdss/marvin#436]
When a function with an API request is called (in this case calling a Maps object through MaNGA ID), recently we get an error message, but the object is returned at the same time:
```
>>>maps = Maps(mangaid='1-24124', mode='auto')
Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
['no DB connection found']

>>>maps
<Marvin Maps (plateifu='7991-3703', mode='local', data_origin='file', bintype='SPX', template='GAU-MILESHC')>
```
When we change the `mode` for the function here, we get differences in the error text:
```
>>>mapz = Maps(mangaid='1-250922', mode='local')
['no DB connection found']

>>>mapz
<Marvin Maps (plateifu='8332-9101', mode='local', data_origin='file', bintype='SPX', template='GAU-MILESHC')>
```
We get the same error for the `mangaid2plateifu()` function with `mode='auto'` but not with `mode='remote'`:
```
>>>import marvin
>>>marvin.utils.general.general.mangaid2plateifu('1-24124', mode='auto')
'7991-3703'
Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
['no DB connection found']

>>>import marvin
>>>marvin.utils.general.general.mangaid2plateifu('1-24124', mode='remote')
'7991-3703'
```
Finally, we don't get the error at all when we call the function with PlateIFU instead or MaNGA ID:
```
>>>maps = Maps(plateifu='7991-3703', mode='auto')
>>>maps
<Marvin Maps (plateifu='7991-3703', mode='local', data_origin='file', bintype='SPX', template='GAU-MILESHC')>

>>>maps = Maps(plateifu='7991-3703', mode='remote')
>>>maps
<Marvin Maps (plateifu='7991-3703', mode='remote', data_origin='api', bintype='SPX', template='GAU-MILESHC')>

>>>maps = Maps(plateifu='7991-3703', mode='local')
>>>maps
<Marvin Maps (plateifu='7991-3703', mode='local', data_origin='file', bintype='SPX', template='GAU-MILESHC')>
```

**Desktop**
 -  Jupyterhub version 0.8.1 running on Ubuntu version 16.04 server
 - Chrome used to access Jupyter
 - Marvin 2.2.5

**Additional context**
I've checked to see that we have the `.netrc` permissions set to 600.

**Comment by havok2063** [comment]
It looks the `Marvin Tools` or functions are working properly.  In your examples, the proper objects, i.e. a `maps` or a `plateifu`, are being returned.  The message you are seeing 

`Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
['no DB connection found']`

is coming from a third party error logging package we use called `Sentry`, rather than Marvin itself.  The free version of `Sentry` allows for only a certain number of errors reported per day/month, so there is rate-limit on their API, which we are hitting.  We'll have to look into a solution with `Sentry`, but for now you can ignore these messages and continue to use Marvin normally.

**Comment by albireox** [comment]
I think there are two parts to this problem. On one side, we should be filtering messages like those. I'm not sure how those messages are output but Googling a bit it seems they use the [default logging system](https://docs.sentry.io/clients/python/breadcrumbs/) so it may be possible to do something there.

The other issue is why would Sentry try to log that error. If I follow the logic, it seems that the error happens when @sjshamsi tries to do `mapz = Maps(mangaid='1-250922', mode='local')` with a `mangaid`. In that case `mangaid2plateifu` is called in auto mode, which loops over different ways of converting a mangaid to a plateifu. The first of those methods is using the DB. If there is no DB a MarvinError with the message `'no DB connection found'` is raised, but that error is wrapped in a try-except and `mangaid2plateifu` skips to the next mode. So, that error should never show up in that call mode, and Sentry should not try to log anything.

**Comment by havok2063** [comment]
According to Sentry, we have received the `no DB connection found` error 7.9k times within the past year at least, up to about 12 minutes ago.  So this might be a real bug in our code triggering this.  But also, anytime we raise a `MarvinError` we capture the error and send it to Sentry.  This happens regardless if the raise is wrapped in try-except.  That was our original desired behavior.  If this something we want to change, we'll need to sort out when and how we want to send errors to Sentry.
