### ISSUE TITLE
Add option to config file to define release upon import

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#463]
**Is your feature request related to a problem? Please describe.**
Marvin always defaults to the latest version. This is ok in most cases but a bit frustrating if you really want to work with a different version.

**Describe the solution you'd like**
Add a configuration option to the YAML config file to set the initial MPL/DR.

**Comment by havok2063** [comment]
This is reasonable enough.  It makes sense to do if people want to stick with using an older dataset.  It's not the cause of the current RTD error, but it's probably not a bad idea to do anyways.  The RTD error ultimately is due to a drpall path exception raise when the release gets set because the MANGA_SPECTRO_REDUX environment variable isn't defined.  This cropped up under the pristine RTD build environment and the recent reorganization of the `config`.  I'm fixing that now.
