### ISSUE TITLE
Correct bug in sigmacorr map

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#464]
MPL-6/7 have a bug in the dispersion correction that affects the `stellar_sigmacorr` map and, thus, the instrumental broadening correction. We agreed to not patch this in DAP until MPL-8 and make the following changes to Marvin to address the problem:

- [ ] The `Map.inst_sigma_correction` method will gain a `method` keyword parameter that defaults to `map`, which uses the `stellar_sigmacorr` map as of now. For MPL-6/7 that will fail with a message saying that there is a problem with that extension and suggesting to use `method='resolution_difference'` or similar that will indicate that we want to use a map reconstructed on the fly with the correct code. For MPL-8 with can make that `method='resolution_difference'` fail if we want people to go back to using the DAP Map.
- [ ] @kbwestfall will send a snippet of code to calculate the reconstructed sigmacorr map. It makes use of the DRP dispersion vector.
- [ ] Add tests. @kbwestfall, can you provide a few tests with the wrong and correct values? Ideally using 8485-1901 and MPL-6.
- [ ] We will add a check in the API server that will get the version of marvin you are using and issue a warning about the sigmacorr map if you are trying to access MPL6/7 with an old version of Marvin.
- [ ] For the web, we already have an item in the Maps dropdown menu that shows the stellar sigma corrected map by calling `inst_sigma_correction`. For MPL-6/7 the web will use `method='reconstruct_map'` and show a banner indicating that what we are showing is the corrected version, not the Maps version.
- [ ] Changes to the documentation
    - [ ] Update `Maps.inst_sigma_correction` docstring
    - [ ] Add a section to the Marvin Maps/Map documentation
    - [ ] Modify the description string for `stellar_sigmacorr` in the Marvin DAP datamodel for MPL-6/7 to point to this caveat.
    - [ ] Add an entry to the known issues page
    - [ ] Add an entry to the what's new page
    - [ ] Update tutorials
    - [ ] WP: update tutorials
    - [ ] WP: add an entry to caveats
    - [ ] WP: add note to datamodels

@kbwestfall, @havok2063, @yanrenbin can you check this and add/edit items?

**Comment by kbwestfall** [comment]
Here are the lines of code.  Turns out it was more than two...

You need the NSA redshift (I'm taking it from the DRPall file), the DRP LOGCUBE WAVE and PREDISP extensions, the MAPS STELLAR_VEL extension, and the DAP LOGCUBE MASK extension.  This should work for both VOR10 and HYB10.  This requires that the templates used in the fit were the MILESHC library because of the definition of `sinst_miles`.

```
import numpy
from astropy.io import fits
import astropy.constants

hdu = fits.open('manga-7443-12703-MAPS-VOR10-GAU-MILESHC.fits.gz')

# Speed of light
c = astropy.constants.c.to('km/s').value

# NSA redshift
hdu_drpall = fits.open('drpall-v2_4_3.fits')
indx = hdu_drpall[1].data['PLATEIFU'] == '7443-12703'
z_NSA = hdu_drpall[1].data['NSA_Z'][indx][0]

# Instrumental dispersion of the MaNGA LSF in km/s
hdu_drpcube = fits.open('offset/mpl7/manga-7443-12703-LOGCUBE.fits.gz')
sinst_manga = numpy.ma.MaskedArray(c * hdu_drpcube['PREDISP'].data 
                                        / hdu_drpcube['WAVE'].data[:,None,None],
                                   mask=numpy.invert(hdu_drpcube['PREDISP'].data > 0))

# Stellar Doppler shift
z_stars = (1+hdu['STELLAR_VEL'].data/c)*(1+z_NSA) - 1
wave_rest = hdu_drpcube['WAVE'].data[:,None,None]/(1+z_stars)

# Instrumental dispersion of MILESHC library at the appropriate wavelength in km/s
sinst_miles = 2.54*c/wave_rest/numpy.sqrt(8*numpy.log(2))

# Compute the quadrature difference in the sigma_inst
dsinst2 = numpy.square(sinst_manga) - numpy.square(sinst_miles)

# The spectral range over which the MaNGA spectra are modeled
hdu_cube = fits.open('manga-7443-12703-LOGCUBE-VOR10-GAU-MILESHC.fits.gz')
mask = hdu_cube['MASK'].data > 0
dsinst2[mask] = numpy.ma.masked

# Average the resolution difference over the fitted region to produce
# the sigma correction
sigmacorr = numpy.ma.sqrt(numpy.ma.mean(dsinst2, axis=0)).filled(0.0)
```

Alternatively, it may be easier to read the correction from the reference file.  Here's the code to do that:

```
from astropy.io import fits
from mangadap.util.fitsutil import DAPFitsUtil

hdu = fits.open('manga-7443-12703-MAPS-VOR10-GAU-MILESHC.fits.gz')

# Get the correction values
hdu_ref = fits.open('ref/manga-7443-12703-SNRG-VOR10-GAU-MILESHC.fits.gz')
sigmacorr_values = hdu_ref['PAR'].data['SIGMACORR_SRES'].copy()

# Get the observed sigma and reconstruct the sigma correction map
binid = hdu['BINID'].data[1,:,:]
sigmacorr = DAPFitsUtil.reconstruct_map(binid.shape, binid.ravel(), sigmacorr_values)
```

You can see the relevant DAPFitsUtil function [here](https://github.com/sdss/mangadap/blob/c31a945fac7bb18190fbac02bda4577d4dd387e9/python/mangadap/util/fitsutil.py#L372), which you should feel free to copy/rewrite as a Marvin function.

I've checked that both approaches are consistent for 7815-3702, despite the above being written for 7443-12703 (because this is what's in the tutorial and I'm going to send this to Dave and Amy next).  There are subtle differences (mostly <1 km/s, except at the edges of the FOV) because the masking used in the direct calculation isn't exactly what is used in the fitting itself and provided in the reference files.  It's non-trivial to reconstruct the exact mask used in the stellar continuum fit, and these differences are marginal to the corrected dispersion.

Once the code is written in Marvin, I can write a test that uses 8485-1901 and MPL-6.

**Comment by albireox** [comment]
Thanks @kbwestfall, I'll give this a try. I think we want to stick with using DRP, Maps, and ModelCube, and not use the reference file. Getting all that information is a bit more than we expected but all should be already implemented and if the user doesn't have all the pieces downloaded they can be gotten over the API.

You say this approach works for `VOR10` and `HYB10`. Does it also work for `SPX`? Doing this only for MILES should not be a problem. The `inst_sigma_correction` method already fails if you try to use it with MPL-4.

**Comment by albireox** [comment]
This has been taken care of by @kbwestfall with a patch to the MAPS files so this hack is no longer necessary. We'll need to reload the MAPS data (at least for `stellar_sigmacorr`) in the DB for `MPL-6` and `MPL-7` but we can close this now.
