### ISSUE TITLE
MapSpec view galaxy image not loading

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#542]
Galaxy image not loading when selecting a specific plate-ifu. Images are broken links.

Using Chrome browser.

Public Marvin website.

**Comment by bretthandrews** [comment]
Thanks for submitting this issue Kate! Try logging into a DR15 site like this one and then reloading:

https://dr15.sdss.org/sas/dr15/manga/spectro/redux/v2_4_3/

**Comment by bretthandrews** [comment]
The wiki is updated to let other vetters know about this step.

**Comment by KateRowlands** [comment]
Thanks! Now the image loading works.

**Comment by havok2063** [comment]
I'm going to put this here.   https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
This is true for Chrome, and other modern browsers, as well.  

"Authentication of cross-origin imagesSection
A potential security hole that has recently been fixed by browsers is authentication of cross-site images. From Firefox 59 onwards, image resources loaded from different origins to the current document are no longer able to trigger HTTP authentication dialogs (bug 1423146), preventing user credentials being stolen if attackers were able to embed an arbitrary image into a third-party page."
