### ISSUE TITLE
nbconvert kernel error

### ISSUE THREAD

**Issue by bretthandrews** [sdss/marvin#612]
**Describe the bug**
When compiling on `readthedocs`, we get this error for trying to convert `lean_tutorial.ipynb` to `lean_tutorial.rst`:

```
NoSuchKernel in tutorials/notebooks/lean-tutorial.ipynb:
No such kernel named python3
```

see https://readthedocs.org/projects/sdss-marvin/builds/8353382/

However, I can't see any obvious problems with the html output: https://sdss-marvin.readthedocs.io/en/latest/tutorials/lean-tutorial.html

**Comment by havok2063** [comment]
I think we don't see any error with the html output because there is an existing `rst` file which compiles to` html` when we build.   I'm using `nbconvert` to convert my query notebook directly into html.  If I recall, I think you created a main `rst` file for the tutorial with the available notebook file to download, with no expectations to dynamically build it to html.  And I think `nbconvert` is searching for any notebooks to build in the `tutorials/notebooks` directory.

**Comment by bretthandrews** [comment]
nbsphinx docs on disabling/enabling auto-execution with readthedocs: https://nbsphinx.readthedocs.io/en/0.4.2/never-execute.html#Explicitly-Dis-/Enabling-Notebook-Execution

**Comment by havok2063** [comment]
Closing this.  If this is still an issue with the latest marvin, we can open a new ticket.
