### ISSUE TITLE
static images do not load for collab marvin web

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#631]
**Describe the bug**
The static images for marvin do not load in the collaboration version of the website.  See the main page.  However, they load when you go to https://lore.sdss.utah.edu/marvin/, which sas.sdss.org redirects to.  This suggests maybe the sas.sdss.org domain isn't correctly proxying the static nginx location.

**To Reproduce**
Go to the https://sas.sdss.org/marvin.
Look at it!  

**Expected behavior**
The static images should load

**Comment by joelbrownstein** [comment]
Hi Brian,

It looks like this is being caused by a bad location for /mvarin/static in 
https://github.com/sdss/config/blob/sas-vm/nginx/conf.d/default.conf

I tested replacing line 
https://github.com/sdss/config/blob/sas-vm/nginx/conf.d/default.conf#L489
with
https://github.com/sdss/config/blob/sas-vm/nginx/conf.d/default.conf#L449
which fixes the location to at least point to an existent path at sas-vm:
/home/manga/software/git/manga/marvin/current/python/marvin/web/static;
which fixes the proxy.

If this is OK, please make the fix in github and I'll pull it to sasvm to make it permanent.

Cheers, Joel

**Comment by havok2063** [comment]
Hi @joel, 

Thanks for looking into this.  I've committed a change to try out the proxy pass solution.  I've commented out all the old `/marvin/static` locations and added  the following 

```
    location /marvin/static {
        proxy_pass https://lore.sdss.utah.edu/marvin/static;
        #proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_connect_timeout 1000;
        proxy_read_timeout 1000;
    }
```
Can you pull to sasvm and then I can test it out?  If it doesn't work we can just manually change the link.

**Comment by havok2063** [comment]
This has been fixed.
