### ISSUE TITLE
Make our version of sqlalchemy-boolean-search pip-installable

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#645]
How should we do this? Is there a chance to get out changes merged to the main repo?

**Comment by havok2063** [comment]
The plan is to deprecate this package.  All further work on this package will be in https://github.com/havok2063/boolean_parser, make this pip-installable, and replace all the code with this package.  At that point I will probably make this repo read-only.  The original repo has not been updated since 2015 so it is no longer being maintained.

**Comment by havok2063** [comment]
Completed.
