### ISSUE TITLE
Make wtforms-alchemy a pip-installable package

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#646]
Should we create our own package or try to merge this back?

**Comment by havok2063** [comment]
We only made one change to this repo.  The owner did not want to merge back into master because of reasons.  It was a small change and he didn't accept the PR.  This probably doesn't warrant making a new pip product, but we could probably move the dependency to the pip requirements and tell it to directly install from the github repo.

**Comment by havok2063** [comment]
Completed.  This is now released as `marvin-wtforms-alchemy`
