### ISSUE TITLE
Unable to display maps for non-Primary plates

### ISSUE THREAD

**Issue by KateRowlands** [sdss/marvin#671]
When I try to download the map for 8934-9101 (which I think is a Coma plate) I get the following error in Marvin web (and similar crash in the tools):

Error: Error getting maps: Could not get map for: stellar_vel, emline_gflux:ha_6564, specindex:d4000. Please select another.

**Comment by KateRowlands** [comment]
Also happening for 8568-12701, 8459-12701. Some of these are in the secondary sample.

from marvin.tools.maps import Maps
maps = Maps(plateifu='8459-12701')
print(maps)

---------------------------------------------------------------------------
BrainError                                Traceback (most recent call last)
//anaconda3/envs/python3/lib/python3.6/site-packages/marvin/tools/maps.py in _load_maps_from_api(self)
    370         try:
--> 371             response = self._toolInteraction(url_full)
    372         except Exception as ee:

//anaconda3/envs/python3/lib/python3.6/site-packages/marvin/tools/core.py in _toolInteraction(self, url, params)
    131         params = params or {'release': self._release}
--> 132         return marvin.api.api.Interaction(url, params=params)
    133 

//anaconda3/envs/python3/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py in __init__(self, route, params, request_type, auth, timeout, headers, stream, datastream, send, base)
     54         if self.url and send:
---> 55             self._sendRequest(request_type)
     56         elif not self.url and send:

//anaconda3/envs/python3/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py in _sendRequest(self, request_type)
    292             # Check the response if it's good
--> 293             self._checkResponse(self._response)
    294 

//anaconda3/envs/python3/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py in _checkResponse(self, response)
    256                 self._closeRequestSession()
--> 257                 raise BrainError('Something went wrong on the server side: {0}'.format(errorMsg))
    258 

BrainError: Something went wrong on the server side: Failed to retrieve maps 8459-12701: list index out of range

During handling of the above exception, another exception occurred:

MarvinError                               Traceback (most recent call last)
<ipython-input-28-5f5995f1b246> in <module>
      1 from marvin.tools.maps import Maps
----> 2 maps = Maps(plateifu='8459-12701')
      3 print(maps)

//anaconda3/envs/python3/lib/python3.6/site-packages/marvin/tools/maps.py in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, nsa_source, bintype, template, template_kin)
    110             self._load_maps_from_db(data=self.data)
    111         elif self.data_origin == 'api':
--> 112             self._load_maps_from_api()
    113         else:
    114             raise marvin.core.exceptions.MarvinError(

//anaconda3/envs/python3/lib/python3.6/site-packages/marvin/tools/maps.py in _load_maps_from_api(self)
    372         except Exception as ee:
    373             raise marvin.core.exceptions.MarvinError(
--> 374                 'found a problem when checking if remote maps exists: {0}'.format(str(ee)))
    375 
    376         data = response.getData()

MarvinError: found a problem when checking if remote maps exists: Something went wrong on the server side: Failed to retrieve maps 8459-12701: list index out of range.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

**Comment by KateRowlands** [comment]
This is MPL-7/DR15 collab version.

**Comment by albireox** [comment]
I'm able to reproduce this but I'm not sure where the problem is. The MAPS seem to be loaded in the DB for MPL-7. I don't see it for MPL-8, which confuses me a bit. Is it being loaded from a file remotely?

The error seems to suggest some empty list somewhere in the loading but it's difficult to say. I don't seem to be able to see the Sentry reports anymore so maybe if @havok2063 can look into those (there should be one from ~11:30 today) that would be useful.

**Comment by havok2063** [comment]
@KateRowlands I've started looking into this after our previous conversation.  The problem is these galaxies don't have their HDU extensions loaded into the database.  There are 78 in MPL-7 and 1 in MPL-8.  The galaxies don't appear to have any connection with each other.  I think you just happened to find a fair number of ones which indicated a problem.  

Each `dapdb.File` object in the database has a `primary_header` property that Marvin `Maps` accesses to get the primary header.  When the HDUs are not loaded, the `Maps` objects cannot grab any HDU information on instantiation, so it fails.  

This falls back on the problems we experienced during the initial load of DR15 data into the database, mainly due to issues in the parallelization of the database load on the cluster.  

I'll reload the HDUs and let you know when things are fixed.

**Comment by havok2063** [comment]
@KateRowlands I have reloaded the missing HDUs and checked a few plate-IFUS on the web.  Things seem to load now.   Can you check some of your targets?  If everything looks ok to you, then we can consider this closed.

**Comment by havok2063** [comment]
@albireox You should still have access to Sentry.   It's using your uw email address.  If you want to use your gmail one, I think that needs reactivation.

**Comment by KateRowlands** [comment]
The problem seems to be fixed! Thanks so much for your help!
