### ISSUE TITLE
MapSpec View disappearing in web version

### ISSUE THREAD

**Issue by astrolojo** [sdss/marvin#684]
**Describe the bug**
The "Galaxy Image" panel in the web version of Marvin does not appear while logged in as an anonymous collaborator (i.e., using the default SDSS login credentials). Images do not load and thus cannot be interacted with in MapSpec View, meaning spaxels (other than the default central spaxel spectrum) cannot be examined in a browser. I have not tested whether this issue occurs when using individual login credentials instead of the default/generic ones.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a random galaxy in DR15 in Marvin Web that is accessible to the public (these data are hosted on https://dr15.sdss.org/marvin). Turn on MapSpec View. The interactive image should appear and allow the user to click around to view different spaxels.
2. Login using the default SDSS credentials, and find the same galaxy in DR15 while logged in as an anonymous collaborator (these data are hosted on https://lore.sdss.utah.edu/marvin/). The Galaxy Image may or may not load before turning on MapSpec View.
3. Turn on MapSpec View. An empty container corresponding to the Galaxy Image loads, as does the central spaxel's spectrum in the adjacent container. 
4. Mousing over the empty Galaxy Image container displays the spaxel coordinates, but clicking generates the error: "requested pixel coords are outside the image range". See the screenshot below for an example. 

**Screenshots**
<img width="1284" alt="Screen Shot 2019-11-13 at 1 57 29 PM" src="https://user-images.githubusercontent.com/57727969/68799103-34549c80-061d-11ea-887a-a6ceee8cd465.png">

**Desktop**
 - OS: OSX Yosemite (10.10.2)
 - Browser: Firefox (vers. 70.0)
 - Marvin Web version 2.3.2

**Comment by havok2063** [comment]
@LoJo94 This is a known issue due to the fact the MaNGA optical images are hosted on a different domain server than the Marvin web server.  That domain server requires separate authentication.  I am currently working on a solution that will enable cross-origin resource sharing (CORS) between the Marvin web server and `data.sdss.org`.  Until then, as a temporary solution, you should be able to separately authenticate on `data.sdss.org`.  In a new tab in your browser, go to `https://data.sdss.org/sas/mangawork/manga/` and authenticate as usual.  Then refresh the Marvin page.  The images should load and all interaction should be available.

**Comment by havok2063** [comment]
This should be resolved now that everything is public.  You may want to switch to dr17.sdss.org/marvin.
