### ISSUE TITLE
AttributeError: 'FlaskParser' object has no attribute 'location_handler'

### ISSUE THREAD

**Issue by izkgao** [sdss/marvin#700]
**Describe the problem**
I tried to import marvin after installing on a conda environment via pip, but this attribute error occurred.

**To Reproduce**
1. install sdss-marvin via pip
2. import marvin using jupyter notebook or spyder
3. error occurs

**Expected behavior**
No error occurs.

**Screenshots**
![image](https://user-images.githubusercontent.com/16133788/76838218-da840d80-686e-11ea-82a7-f9dd4d0454fb.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Comment by havok2063** [comment]
Hi @izkgao.  This error is due to the latest update in the `webargs` python package, the `6.0.` series.  A fix will be released soon.  Temporarily you can downgrade to the latest `5.5.x` version of `webargs`, with `pip install webargs==5.5.3`.  

Also, to eliminate a possible package version mismatch you may experience with `networkx`, please install version `2.3` with `pip install networkx==2.3`

**Comment by izkgao** [comment]
After I tried the solution @havok2063 provided, the problem solved. I can import `marvin` now.
Thank you so much.
