### ISSUE TITLE
cannot return wcs.crpix in query

### ISSUE THREAD

**Issue by bbemc2** [sdss/marvin#738]
**Describe the bug**
cannot return wcs.crpix in query

**To Reproduce**

from marvin.tools.query import Query
my_filter = 'nsa.elpetro_logmass < 9'
rp = ['wcs.crpix1', 'wcs.crpix2']

q = Query(search_filter=my_filter, return_params=rp)

**Screenshots**
MarvinError: API Query call failed: Requests Http Status Error: 500 Server Error: INTERNAL SERVER ERROR for url: https://dr15.sdss.org/marvin/api/query/cubes/
Error accessing https://dr15.sdss.org/marvin/api/query/cubes/: 500-Internal Server Error.

**Desktop (please complete the following information):**
 - iOS

**Comment by havok2063** [comment]
@bbemc2 Thanks! I'll try to dig in and see if I can find the problem.

**Comment by havok2063** [comment]
@bbemc2 The issue was that some of the columns in the `wcs` database table, including the `crpix` columns, were an unnecessary `numeric` database column type.  This was causing errors during the JSON serialization process when returning your API request.  I've changed the column types to be either integer or double precision and your query now works now for.  Can you check to see if it works for you?

**Comment by bbemc2** [comment]
It works now! Thank you very much!
