### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by astrosteph** [sdss/marvin#740]
Running scripts which usually work, I have the usual collaboration authentication password in the netrc file, and the marvin.yml file set up with a JSON token. 

Ran scripts and get authentication error for trying to access remote maps in MPL-11. This is also reproduced if I try to access MPL-10. 

```

File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/tools/maps.py", line 113, in __init__
    self._load_maps_from_api()
  File "/home/sc381/anaconda3/lib/python3.7/site-packages/marvin/tools/maps.py", line 382, in _load_maps_from_api
    'found a problem when checking if remote maps exists: {0}'.format(str(ee)))
marvin.core.exceptions.MarvinError: found a problem when checking if remote maps exists: API Authentication Error: {'msg': 'Token has expired'}. Please check your token or login again for a fresh one.. .

```

Used config.login and config.token to update and replace the token in the marvin.yml file. 

Error persists even with new token

System: 
Linux Mint
Marvin version 2.6.0

**Comment by havok2063** [comment]
Hi @astrosteph hmm, I can't seem to reproduce your error.  My token still works when retrieving remote Maps.  Which maps file are you trying to retrieve remotely?  When you are calling `config.login`, are you specifying the keyword`refresh=True`.  This will force Marvin to generate a new token.   Otherwise just calling `config.login()` will re-use the same token if one is already set.

**Comment by astrosteph** [comment]
Hey! My mistake, I did not specifiy the refresh. Thank you

**Comment by havok2063** [comment]
@astrosteph Great!  Don't forget to copy the new token into your `marvin.yaml` config file to preserve it!
