### ISSUE TITLE
Import error: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by CptnN3MO** [sdss/marvin#791]
**Describe the bug**
Unable to import escape or subsequent pacages

from jinja2 import escape
     15 from jinja2 import Markup
     16 from werkzeug.exceptions import abort

ImportError: cannot import name 'escape' from 'jinja2' (/home/cptnn3mo/.local/lib/python3.10/site-packages/jinja2/__init__.py)

**To Reproduce**
Steps to reproduce the behaviour:
import marvin

**Expected behaviour**
expected to install normally

**Screenshots**
![Screenshot from 2022-11-25 17-01-11](https://user-images.githubusercontent.com/117912584/203976606-a479f2a7-fbec-47e1-a073-be9d502b9e82.png)

**Desktop (please complete the following information):**
 - OS: Ububtu- latest
 - Version of Marvin latest

**Comment by havok2063** [comment]
@CptnN3MO For now try downgrading `jinja2` to < 3.1, `pip install -U "jinja2>3,<3.1"`.  We can't update `jinja2` and `flask` yet to their latest versions due to an issue with the `flask-jwt-extended` dependency which implemented a lot of breaking changes with version >4.  I'll need to spend some time fixing those.

**Comment by havok2063** [comment]
You can also try upgrading `jinja2` and `flask` but pinning the `werkzeug` dependency to >2, <2.1

**Comment by CptnN3MO** [comment]
Thank you for that, that works out perfectly.
